"""Solution representation for RMS optimisation problems."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Optional

import pandas as pd


@dataclass
class ScheduleSolution:
    """Container for schedules generated by optimisation algorithms."""

    schedule: pd.DataFrame
    metrics: Dict[str, float] = field(default_factory=dict)
    metadata: Optional[Dict[str, str]] = None

    def to_dict(self) -> Dict[str, float]:
        return self.metrics.copy()
