"""Solution representation for RMS optimisation problems."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Optional

import pandas as pd


@dataclass
class ScheduleSolution:
    """Container for schedules generated by optimisation algorithms."""

    schedule: pd.DataFrame
    metrics: Dict[str, float] = field(default_factory=dict)
    metadata: Optional[Dict[str, str]] = None

    def __post_init__(self) -> None:
        if not isinstance(self.schedule, pd.DataFrame):
            raise TypeError("schedule must be a pandas DataFrame")
        if not self.metrics:
            from core.metrics import evaluate_schedule

            self.metrics = evaluate_schedule(self.schedule)

    def to_dict(self) -> Dict[str, float]:
        return self.metrics.copy()
